services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./users-init.js:/docker-entrypoint-initdb.d/users-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    networks:
      - migration_network

  migration:
    build: .
    container_name: migration_app
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: python migration.py
    environment:
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${MONGO_DATABASE}
    networks:
      - migration_network

volumes:
  mongo_data:

networks:
  migration_network: