version: '3.8'


services:

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: sante_db
    networks:
      - migration_network

  migration:
    build: .
    container_name: migration_app
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: python migration.py
    environment:
      MONGO_URI: mongodb://admin:admin123@mongo:27017/?authSource=admin
      DB_NAME: sante_db
    networks:
      - migration_network

volumes:
  mongo_data:

networks:
  migration_network:
    driver: bridge