version: '3.8'

services:

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - migration_network

  migration:
    build: .
    container_name: migration_app
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: python migration.py
    networks:
      - migration_network

volumes:
  mongo_data:

networks:
  migration_network: